[package]
name = "micro_bit"
version = "0.1.0"
edition = "2021"

[dependencies]
microbit-v2 = "0.15.1"
panic-halt = "1.0.0"
cortex-m = {version = "0.7.7", features = ["critical-section-single-core"]}
cortex-m-rt = "0.7.5"
defmt-rtt = "0.4.0"
defmt = "0.3.10"
